version: "3.1"

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "0.0.0.0:27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: sophie
      MONGO_INITDB_ROOT_PASSWORD: ticket
      MONGO_INITDB_DATABASE: ticket-manager

volumes:
  mongo-data:
    driver: local